# Generated by Django 3.1.3 on 2020-12-02 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=25)),
                ('phone_number', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=40)),
                ('on_site_since', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OfferItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('count', models.IntegerField()),
                ('release_date', models.DateField()),
                ('category', models.CharField(choices=[('CA1', 'Category 1'), ('CA2', 'Category 2')], max_length=5)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='ecommerce.seller')),
            ],
        ),
    ]
