# Generated by Django 3.1.3 on 2020-12-02 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_auto_20201201_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='mark',
            field=models.IntegerField(default=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='grades.subject'),
        ),
    ]
